// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxwssmqegawhaxvnoktp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4d3NzbXFlZ2F3aGF4dm5va3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NTAwNjQsImV4cCI6MjA5MDUyNjA2NH0.X9UdmqYLTW06WeV0uNOk1Ki96bT0yUpyyG6qZ8e7bVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});